# Generated by Django 3.1 on 2020-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstaap', '0003_auto_20200920_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
