# Generated by Django 3.1 on 2020-09-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstaap', '0004_auto_20200920_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
